/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Parking;
import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordcon = new javax.swing.JLabel();
        admincon = new javax.swing.JLabel();
        admintitle = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        clear = new javax.swing.JButton();
        login = new javax.swing.JButton();
        container = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordcon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordcon.setForeground(new java.awt.Color(242, 242, 242));
        passwordcon.setText("Password:");
        getContentPane().add(passwordcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 90, 50));

        admincon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admincon.setForeground(new java.awt.Color(242, 242, 242));
        admincon.setText("Name:");
        getContentPane().add(admincon, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 70, 50));

        admintitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admintitle.setForeground(new java.awt.Color(242, 242, 242));
        admintitle.setText("Admin Login");
        getContentPane().add(admintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 140, 50));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 120, 30));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 120, 30));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, -1, -1));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, -1));

        container.setText("jLabel1");
        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 370, 360));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Documents\\carparking.jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        name.setText("");
        password.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
      String sql="select * from admin where name = ? and password =?";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/carparking", "root", "");
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1,name.getText());
            pstmt.setString(2,new String(password.getPassword()));
            
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Welcome " + name.getText(), "Succsesful Login", JOptionPane.PLAIN_MESSAGE);
                new AdminPanel().setVisible(true);
                dispose();
               }else{
                JOptionPane.showMessageDialog(null,"Invalid Username Or Password", "Unsuccessfull Login", JOptionPane.ERROR_MESSAGE);
            }conn.close();   
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       
 
    }//GEN-LAST:event_loginActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admincon;
    private javax.swing.JLabel admintitle;
    private javax.swing.JLabel background;
    private javax.swing.JButton clear;
    private javax.swing.JLabel container;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordcon;
    // End of variables declaration//GEN-END:variables
}
