/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Parking;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author ADMIN
 */
public class Details extends javax.swing.JFrame {

    /**
     * Creates new form UserSignup
     */
    public Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        model = new javax.swing.JTextField();
        Title3 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        spaces = new javax.swing.JTextField();
        time = new javax.swing.JComboBox<>();
        Title = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        logout = new javax.swing.JToggleButton();
        panel = new javax.swing.JToggleButton();
        container = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 120, -1));

        Title3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title3.setForeground(new java.awt.Color(242, 242, 242));
        Title3.setText("Car Model:");
        getContentPane().add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 100, 40));

        Title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title1.setForeground(new java.awt.Color(242, 242, 242));
        Title1.setText("Time:");
        getContentPane().add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 100, 40));

        Title2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(242, 242, 242));
        Title2.setText("Spaces:");
        getContentPane().add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 110, 40));
        getContentPane().add(spaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 120, -1));

        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------", "1800HRS - 2200HRS", "2200HRS - 0000HRS", "0000HRS - 0400HRS", "0400HRS - 0600HRS" }));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 130, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(242, 242, 242));
        Title.setText("Space Booking");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 130, 40));

        login.setText("Book");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, -1));

        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, -1, -1));

        panel.setText("Back to Panel");
        panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelActionPerformed(evt);
            }
        });
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, -1));

        container.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Documents\\carparking.jpg")); // NOI18N
        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 320, 460));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Documents\\carparking.jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1044));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        spaces.setText("");
        time.setSelectedIndex(0);
        model.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
       try{
       Class.forName("com.mysql.jdbc.Driver");
       Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/carparking", "root", "");
       
       String sql = "insert into registration values(?, ?, ?)";
       PreparedStatement pstmt= conn.prepareStatement(sql);
       pstmt.setString(1,spaces.getText());
       
        String tym;
        tym= time.getSelectedItem().toString();
        pstmt.setString(2,tym);
       pstmt.setString(3,model.getText());
       
       pstmt.executeUpdate();
       JOptionPane.showMessageDialog(null, "Booking Successful");
       conn.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       }
    }//GEN-LAST:event_loginActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new Index().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelActionPerformed
        // TODO add your handling code here:
        new AdminPanel().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel background;
    private javax.swing.JButton clear;
    private javax.swing.JLabel container;
    private javax.swing.JButton login;
    private javax.swing.JToggleButton logout;
    private javax.swing.JTextField model;
    private javax.swing.JToggleButton panel;
    private javax.swing.JTextField spaces;
    private javax.swing.JComboBox<String> time;
    // End of variables declaration//GEN-END:variables
}
