/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Parking;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author ADMIN
 */
public class UserSignup extends javax.swing.JFrame {

    /**
     * Creates new form UserSignup
     */
    public UserSignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        model = new javax.swing.JTextField();
        Title4 = new javax.swing.JLabel();
        Title5 = new javax.swing.JLabel();
        plate = new javax.swing.JTextField();
        Title3 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        back = new javax.swing.JToggleButton();
        clear = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        container = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 120, -1));

        Title4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title4.setForeground(new java.awt.Color(242, 242, 242));
        Title4.setText("Password:");
        getContentPane().add(Title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 130, 40));

        Title5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title5.setForeground(new java.awt.Color(242, 242, 242));
        Title5.setText("Number Plate:");
        getContentPane().add(Title5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 130, 40));
        getContentPane().add(plate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 120, -1));

        Title3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title3.setForeground(new java.awt.Color(242, 242, 242));
        Title3.setText("Car Model:");
        getContentPane().add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 100, 40));

        Title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title1.setForeground(new java.awt.Color(242, 242, 242));
        Title1.setText("Full Name:");
        getContentPane().add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 100, 40));

        Title2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(242, 242, 242));
        Title2.setText("National Id:");
        getContentPane().add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 110, 40));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 120, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 120, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 120, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(242, 242, 242));
        Title.setText("Registration");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 130, 40));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, -1));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, -1));

        jToggleButton1.setText("Login");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, -1, -1));

        container.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Documents\\carparking.jpg")); // NOI18N
        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 320, 460));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Documents\\carparking.jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1044));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        id.setText("");
        name.setText("");
        model.setText("");
        plate.setText("");
        password.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
       try{
       Class.forName("com.mysql.jdbc.Driver");
       Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/carparking", "root", "");
       
       String sql = "insert into users values(?, ?, ?, ?, ?)";
       PreparedStatement pstmt= conn.prepareStatement(sql);
       pstmt.setString(1,id.getText());
       pstmt.setString(2,name.getText());
       pstmt.setString(3,model.getText());
       pstmt.setString(4,plate.getText());
       pstmt.setString(5,password.getText());
       
       pstmt.executeUpdate();
       JOptionPane.showMessageDialog(null, "Signup Successful");
       conn.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       }
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Index().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        new UserLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title5;
    private javax.swing.JToggleButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton clear;
    private javax.swing.JLabel container;
    private javax.swing.JTextField id;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton login;
    private javax.swing.JTextField model;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField plate;
    // End of variables declaration//GEN-END:variables
}
